### ISSUE TITLE
Rahul: speed it up

### ISSUE THREAD

**Issue by username2112** [username2112/Space-Project#41]
even at 60FPS the game feels slow, speed everything up a bit

**Comment by MohammedMohiuddin1** [comment]
yea we will hopefully go back to the faster version of the game, we were just testing for the past few weeks because the player had some lag issues when the game was faster but i think thats fixed we will be looking forward to adding a faster version of the game

**Comment by username2112** [comment]
Noted, in a previous suggestion it has been asked for us to add incrementing speed as levels progress, as such we feel that the current speed is fine.
