### ISSUE TITLE
Omar Madhani: Suggestions/Additions

### ISSUE THREAD

**Issue by OmarMadhani** [username2112/Space-Project#46]
After testing your game, I would highly recommend it. A few additions to the game that I would suggest include…

-Power Ups across the map (increased speed, rapid fire, etc.)
-Perhaps the player could be able to angle their shots
-Boss homing missile that lasts for a few seconds.
-At higher levels, boss AI will attempt to avoid your shots
-Different game modes
-Multiple lives
-In game currency (coins) players could capture during play
     - Players could redeem Power Ups/new ships/ammo with the coins.

Thank you,

Omar Madhani

**Comment by MohammedMohiuddin1** [comment]
the boss movement, angled shots, and multiple lives have been added to the latest version of the game, we had the game speed increasing in the middle but there were some lag issues with the player so we are currently testing, powerup/consumables will hopefully be added in the game soon
thanks for the new requests we will be looking forward to adding them soon.

**Comment by username2112** [comment]
we have noted your suggestions and have implemented a number of them, but as the end of the project approaches it is unlikely we will implement any more features.
