### ISSUE TITLE
Images are bound in one place

### ISSUE THREAD

**Issue by OroArmor** [username2112/Space-Project#70]
Each image is defined in the class itself, moving to a new class with a image path is not only better and easier to update, it also allows to create resource packs

**Comment by OroArmor** [comment]
[Pull request i created](https://github.com/username2112/Space-Project/pull/69)

**Comment by username2112** [comment]
Thank you for your suggestion, we where aware of this and had it in our development queue and appreciate your help. Your pull request has been committed.
