### ISSUE TITLE
BUFF the BOMB SHOT

### ISSUE THREAD

**Issue by MohammedMohiuddin1** [username2112/Space-Project#97]
ok so after playing the latest version of the game i noticed that the player now has 5 bombs per level, i tried using these bombs and they do nothing they max these bombs do is kill 2 aliens, i find it difficult to get passed level 8 i recommend yall buff it as soon as possible cuz its literally the same thing as the normal shot

**Comment by username2112** [comment]
the max the bombs can kill currently is actually 4 but rest assured we are looking to buff the bomb shot while we rework hitboxes. As currently the reason the bomb can only kill a couple aliens is due to how the hitboxes work currently, we hope this will be fixed after the holidays.

**Comment by MohammedMohiuddin1** [comment]
ok thanks looking forward to play it after the holidays
